version: '3.0'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musement
      MYSQL_USER: musement_user
      MYSQL_PASSWORD: password
