version: '3.0'

services:
  php:
    build:
      context: ./
    ports:
      - '9000:9000'
    depends_on:
      - db
    environment:
      XDEBUG_MODE: debug,coverage
      DATABASE_URL: "mysql://musement_user:password@db:3306/musement"
      MUSEMENT_API_URL: 'https://api.musement.com'
      WEATHER_API_URL: 'https://api.weatherapi.com'
      WEATHER_API_TOKEN: 'ef11613d2bc9432c9af212308222402'
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musement
      MYSQL_USER: musement_user
      MYSQL_PASSWORD: password
