version: '3.0'

services:
  php:
    build:
      context: ./
    ports:
      - '9000:9000'
    depends_on:
      - db
    environment:
      APP_ENV: dev
      KERNEL_CLASS: 'App\Kernel'
      APP_SECRET: '4c93e7a37de6087eff5c196b8d6ecc8e'
      SYMFONY_DEPRECATIONS_HELPER: 999999
      PANTHER_APP_ENV: anther
      PANTHER_ERROR_SCREENSHOT_DIR: ./var/error-screenshots
      XDEBUG_MODE: debug,coverage
      DATABASE_URL: "mysql://musement_user:password@db:3306/musement"
      MUSEMENT_API_URL: 'https://api.musement.com'
      WEATHER_API_URL: 'https://api.weatherapi.com'
      WEATHER_API_TOKEN: 'ef11613d2bc9432c9af212308222402'
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musement
      MYSQL_USER: musement_user
      MYSQL_PASSWORD: password
